# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-11 13:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_name', models.CharField(max_length=200, verbose_name='Company Type')),
                ('is_valid', models.BooleanField(default=True, verbose_name='Is Valid')),
                ('creation_date', models.DateTimeField(auto_now_add=True, verbose_name='Date Created')),
            ],
        ),
    ]
