# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-06-08 08:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='company_certified_email',
            field=models.EmailField(default='', max_length=200, verbose_name='Company certified email'),
        ),
        migrations.AddField(
            model_name='company',
            name='company_email',
            field=models.EmailField(default='', max_length=200, verbose_name='Company general email'),
        ),
    ]
