# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-11 14:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='companytype',
            old_name='creation_date',
            new_name='created',
        ),
    ]
