# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-08-08 12:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0002_auto_20170608_0833'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='company_certified_email',
            field=models.EmailField(blank=True, default='', max_length=200, verbose_name='Company certified email'),
        ),
        migrations.AlterField(
            model_name='company',
            name='company_email',
            field=models.EmailField(blank=True, default='', max_length=200, verbose_name='Company general email'),
        ),
    ]
