# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-11 14:32
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0002_auto_20160711_1430'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companytype',
            name='created',
        ),
        migrations.AddField(
            model_name='companytype',
            name='creation_date',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='Date Created'),
        ),
    ]
