# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-11 15:05
from __future__ import unicode_literals

import contacts.models
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0003_auto_20160711_1432'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_name', models.CharField(max_length=200, verbose_name='Service Name')),
                ('token', models.CharField(default=contacts.models.create_uid, max_length=200, verbose_name='Token')),
                ('is_valid', models.BooleanField(default=True, verbose_name='Is Valid')),
                ('creation_date', models.DateTimeField(default=datetime.datetime.now, verbose_name='Creation Date')),
                ('activation_date', models.DateTimeField(default=datetime.datetime.now, verbose_name='Activation Date')),
                ('delete_date', models.DateTimeField(blank=True, verbose_name='Delete Date')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
            ],
        ),
        migrations.AlterField(
            model_name='companytype',
            name='creation_date',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='Creation Date'),
        ),
    ]
