# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2026-04-24 13:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0003_auto_20170808_1218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='company_custom_id',
            field=models.CharField(blank=True, help_text='ID of this Company in external systems (eg. Dynamix)', max_length=120, null=True, verbose_name='Custom External ID'),
        ),
    ]
