# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-11 15:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0004_auto_20160711_1505'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='delete_date',
            field=models.DateTimeField(null=True, verbose_name='Delete Date'),
        ),
    ]
