# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-12 09:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0005_auto_20160711_1507'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_custom_id', models.IntegerField(verbose_name='Custom ID')),
                ('company_name', models.CharField(max_length=200, verbose_name='Company Name')),
                ('company_short_name', models.CharField(max_length=200, verbose_name='Company Short Name')),
                ('company_business_name', models.CharField(max_length=200, verbose_name='Company Business Name')),
                ('company_vat_number', models.IntegerField(default=-1, null=True, verbose_name='VAT Number')),
                ('company_tax_code', models.IntegerField(default=-1, null=True, verbose_name='VAT Number')),
                ('company_company_address', models.CharField(max_length=200, verbose_name='Company Address')),
                ('company_cap', models.CharField(max_length=10, verbose_name='CAP')),
                ('company_city', models.CharField(max_length=200, verbose_name='City')),
                ('company_province', models.CharField(max_length=200, null=True, verbose_name='Province')),
                ('company_country', models.CharField(max_length=200, verbose_name='Country')),
                ('company_phone_number', models.CharField(max_length=100, null=True, verbose_name='Phone Number')),
                ('company_fax', models.CharField(max_length=200, null=True, verbose_name='FAX')),
                ('company_website', models.CharField(max_length=200, null=True, verbose_name='WebSite')),
                ('company_notes', models.TextField(null=True, verbose_name='Notes')),
            ],
            options={
                'ordering': ('company_name',),
            },
        ),
        migrations.AlterModelOptions(
            name='companytype',
            options={'ordering': ('type_name',)},
        ),
        migrations.AlterModelOptions(
            name='service',
            options={'ordering': ('service_name',)},
        ),
        migrations.AlterField(
            model_name='service',
            name='notes',
            field=models.TextField(null=True, verbose_name='Notes'),
        ),
        migrations.AddField(
            model_name='company',
            name='company_type',
            field=models.ManyToManyField(to='contacts.CompanyType'),
        ),
    ]
