# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-12 09:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0006_auto_20160712_0928'),
    ]

    operations = [
        migrations.RenameField(
            model_name='company',
            old_name='company_company_address',
            new_name='company_address',
        ),
    ]
