# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-12 09:48
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0007_auto_20160712_0932'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='creation_date',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='Creation Date'),
        ),
    ]
