# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-12 09:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0008_company_creation_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='notes',
            field=models.TextField(verbose_name='Notes'),
        ),
    ]
