# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-12 09:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0009_auto_20160712_0950'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='company_fax',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='FAX'),
        ),
        migrations.AlterField(
            model_name='company',
            name='company_notes',
            field=models.TextField(blank=True, null=True, verbose_name='Notes'),
        ),
        migrations.AlterField(
            model_name='company',
            name='company_province',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Province'),
        ),
        migrations.AlterField(
            model_name='company',
            name='company_tax_code',
            field=models.IntegerField(blank=True, default=-1, null=True, verbose_name='VAT Number'),
        ),
        migrations.AlterField(
            model_name='company',
            name='company_vat_number',
            field=models.IntegerField(blank=True, default=-1, null=True, verbose_name='VAT Number'),
        ),
        migrations.AlterField(
            model_name='company',
            name='company_website',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='WebSite'),
        ),
        migrations.AlterField(
            model_name='service',
            name='notes',
            field=models.TextField(blank=True, null=True, verbose_name='Notes'),
        ),
    ]
