# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-12 09:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0010_auto_20160712_0951'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='company_phone_number',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Phone Number'),
        ),
    ]
