# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-12 10:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0011_auto_20160712_0952'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_username', models.CharField(max_length=200, verbose_name='Contact User Name')),
                ('contact_first_name', models.CharField(blank=True, max_length=200, null=True, verbose_name='Contact First Name')),
                ('contact_last_name', models.CharField(blank=True, max_length=200, null=True, verbose_name='Contact Last Name')),
                ('contact_email', models.EmailField(max_length=200, verbose_name='Contact Email')),
                ('contact_phone', models.CharField(blank=True, max_length=100, null=True, verbose_name='Contact Phone')),
                ('contact_notes', models.TextField(blank=True, null=True, verbose_name='Notes')),
            ],
        ),
    ]
