# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-12 10:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0013_auto_20160712_1013'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactCompanyRelation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contacts.Company')),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contacts.Contact')),
                ('contact_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contacts.ContactType')),
            ],
        ),
    ]
