# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-12 10:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0014_contactcompanyrelation'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ContactCompanyRelation',
            new_name='CCRelation',
        ),
    ]
