# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-12 13:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0015_auto_20160712_1027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='company_tax_code',
            field=models.IntegerField(blank=True, default=-1, null=True, verbose_name='Tax Code'),
        ),
    ]
