# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-13 07:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0017_auto_20160712_1520'),
        ('contacts', '0016_auto_20160712_1535'),
    ]

    operations = [
    ]
