# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-13 08:05
from __future__ import unicode_literals

import contacts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0018_merge'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='company_custom_id',
            field=models.IntegerField(unique=True, verbose_name='Custom ID'),
        ),
        migrations.AlterField(
            model_name='company',
            name='company_tax_code',
            field=models.IntegerField(blank=True, default=-1, null=True, unique=True, verbose_name='Tax Code'),
        ),
        migrations.AlterField(
            model_name='company',
            name='company_vat_number',
            field=models.IntegerField(blank=True, default=-1, null=True, unique=True, verbose_name='VAT Number'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='contact_username',
            field=models.CharField(max_length=200, unique=True, verbose_name='Contact User Name'),
        ),
        migrations.AlterField(
            model_name='service',
            name='token',
            field=models.CharField(default=contacts.models.create_uid, max_length=200, unique=True, verbose_name='Token'),
        ),
    ]
