# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-13 13:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0020_auto_20160713_0811'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='company_is_valid',
            field=models.BooleanField(default=True, verbose_name='Is Valid'),
        ),
    ]
