# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-13 14:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0021_company_company_is_valid'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='contact_company',
            field=models.ManyToManyField(through='contacts.CCRelation', to='contacts.Company'),
        ),
    ]
