# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-14 10:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0023_contact_contact_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='contact_role',
        ),
        migrations.AddField(
            model_name='company',
            name='contact_role',
            field=models.ManyToManyField(through='contacts.CCRelation', to='contacts.ContactType'),
        ),
    ]
