# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-19 10:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0026_auto_20160719_1009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contacttype',
            name='type_name',
            field=models.CharField(max_length=200, unique=True, verbose_name='Contact Type'),
        ),
    ]
