# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-21 13:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0027_auto_20160719_1021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companytype',
            name='type_name',
            field=models.CharField(max_length=200, verbose_name='Company Type'),
        ),
    ]
