# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-21 13:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0028_auto_20160721_1317'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='company_custom_id',
            field=models.IntegerField(null=True, verbose_name='Custom ID'),
        ),
    ]
