# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-28 13:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0029_auto_20160721_1354'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='contact_email_secondary',
            field=models.EmailField(blank=True, max_length=200, null=True, verbose_name='Contact Email Secondary'),
        ),
        migrations.AddField(
            model_name='contact',
            name='contact_phone_secondary',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Contact Phone Secondary'),
        ),
    ]
