# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-28 14:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0030_auto_20160728_1310'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='company_tax_code',
            field=models.CharField(blank=True, max_length=30, null=True, unique=True, verbose_name='Tax Code'),
        ),
        migrations.AlterField(
            model_name='company',
            name='company_vat_number',
            field=models.CharField(blank=True, max_length=30, null=True, unique=True, verbose_name='VAT Number'),
        ),
    ]
