# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-09-15 09:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0032_auto_20160915_0812'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='contact_email',
            field=models.EmailField(blank=True, max_length=200, null=True, verbose_name='Contact Email'),
        ),
    ]
