# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-10-12 14:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0033_auto_20160915_0922'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='company_logo',
            field=models.ImageField(default='None', upload_to='documents/'),
        ),
        migrations.AlterField(
            model_name='company',
            name='company_address',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Company Address'),
        ),
        migrations.AlterField(
            model_name='company',
            name='company_business_name',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Company Business Name'),
        ),
        migrations.AlterField(
            model_name='company',
            name='company_cap',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='CAP'),
        ),
        migrations.AlterField(
            model_name='company',
            name='company_city',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='City'),
        ),
        migrations.AlterField(
            model_name='company',
            name='company_country',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Country'),
        ),
        migrations.AlterField(
            model_name='company',
            name='company_custom_id',
            field=models.IntegerField(blank=True, help_text='ID of this Company in external systems (eg. ESolver)', null=True, verbose_name='Custom External ID'),
        ),
        migrations.AlterField(
            model_name='company',
            name='company_short_name',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Company Short Name'),
        ),
        migrations.AlterField(
            model_name='company',
            name='company_tax_code',
            field=models.CharField(blank=True, help_text='(eg. codice fiscale)', max_length=30, null=True, unique=True, verbose_name='Tax Code'),
        ),
        migrations.AlterField(
            model_name='company',
            name='company_vat_number',
            field=models.CharField(blank=True, help_text='international VAT number (eg. partita IVA)', max_length=30, null=True, unique=True, verbose_name='VAT Number'),
        ),
    ]
