# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-10-12 15:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0034_auto_20161012_1456'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='company_logo',
            field=models.ImageField(default='None', help_text='Company logo', upload_to='uploads/'),
        ),
    ]
