# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-01-07 20:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0039_company_company_mailingaddress'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='company_centralservices_id',
            field=models.IntegerField(blank=True, help_text='ID of this Company in the old CS', null=True, verbose_name='Old Centralservices ID'),
        ),
        migrations.AddField(
            model_name='contact',
            name='contact_centralservices_id',
            field=models.IntegerField(blank=True, help_text='ID of this contact in the old CS', null=True, verbose_name='Old Centralservices ID'),
        ),
        migrations.AlterField(
            model_name='ccrelation',
            name='creation_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Creation Date'),
        ),
        migrations.AlterField(
            model_name='company',
            name='creation_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Creation Date'),
        ),
        migrations.AlterField(
            model_name='companytype',
            name='creation_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Creation Date'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='contact_email',
            field=models.EmailField(default='', max_length=200, unique=True, verbose_name='Contact Email'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='contact_username',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Contact User Name'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='creation_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Creation Date'),
        ),
        migrations.AlterField(
            model_name='contacttype',
            name='creation_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Creation Date'),
        ),
        migrations.AlterField(
            model_name='service',
            name='activation_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Activation Date'),
        ),
        migrations.AlterField(
            model_name='service',
            name='creation_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Creation Date'),
        ),
    ]
