site_name: Contact-tools Documentation
site_description: Documentation for the Contact Tools developed by TOP-IX
site_author: TOP-IX HackAdemy
site_url: http://top-ix.org
repo_url: https://github.com/topix-hackademy/contact-tools

theme: material

docs_dir: documentation/docs
site_dir: documentation/site

pages:
- [index.md, Home]

- ['datamodel/index.md', 'Data Model']
- ['datamodel/company.md', 'Data Model', 'Company']
- ['datamodel/contact.md', 'Data Model', 'Contact']
- ['datamodel/relation.md', 'Data Model', 'Relations']
- ['datamodel/service.md', 'Data Model', 'Service']

- ['api/index.md', 'API']
- ['api/company.md', 'API', 'Company']
- ['api/company_type.md', 'API', 'Company Type']
- ['api/contact.md', 'API', 'Contact']
- ['api/contact_type.md', 'API', 'Contact Type']

- ['deploy/index.md', 'DEPLOY']